In [12]:
import polars as pl

In [13]:
file_path = "../../../data/job_applications.csv"
df_ = pl.read_csv(file_path, n_rows=20)

df_.head()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ applicati ┆ applicant ┆ email     ┆ company   ┆ … ┆ salary_ex ┆ recruiter ┆ interview ┆ notes    │
│ on_id     ┆ _name     ┆ ---       ┆ ---       ┆   ┆ pected    ┆ ---       ┆ _date     ┆ ---      │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│ i64       ┆ str       ┆           ┆           ┆   ┆ i64       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ Jamie     ┆ jamie.san ┆ FoodHub   ┆ … ┆ 45000     ┆ Ana       ┆ null      ┆ null     │
│           ┆ Santos    ┆ tos@examp ┆ PH        ┆   ┆           ┆ Santos    ┆           ┆          │
│           ┆           ┆ le.com    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ Cameron   ┆ cameron.d ┆ GreenCart ┆ … ┆ 45000     ┆ Nina Tan  ┆ null      ┆ Follow   │
│           ┆ Dela Cruz ┆ elacruz@e ┆ PH        ┆   ┆           ┆           ┆           ┆ up next  │
│           ┆           ┆ xample.co ┆           ┆   ┆           ┆           ┆           ┆ week     │
│           ┆           ┆ m         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ Jordan    ┆ jordan.de ┆ DataBridg ┆ … ┆ 50000     ┆ Ken       ┆ 18/03/202 ┆ Need to  │
│           ┆ Dela Cruz ┆ lacruz@ex ┆ e         ┆   ┆           ┆ Flores    ┆ 6         ┆ prepare  │
│           ┆           ┆ ample.com ┆ Analytics ┆   ┆           ┆           ┆           ┆ SQL      │
│ 4         ┆ Taylor    ┆ taylor.ga ┆ HealthFir ┆ … ┆ 35000     ┆ Julia     ┆ 18/08/202 ┆ Need to  │
│           ┆ Garcia    ┆ rcia@exam ┆ st Labs   ┆   ┆           ┆ Cruz      ┆ 6         ┆ prepare  │
│           ┆           ┆ ple.com   ┆           ┆   ┆           ┆           ┆           ┆ SQL      │
│ 5         ┆ Casey     ┆ casey.san ┆ BuildRigh ┆ … ┆ 35000     ┆ Nina Tan  ┆ 22/07/202 ┆ Need to  │
│           ┆ Santos    ┆ tos@examp ┆ t         ┆   ┆           ┆           ┆ 6         ┆ prepare  │
│           ┆           ┆ le.com    ┆           ┆   ┆           ┆           ┆           ┆ SQL      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
df_.schema

Schema([('application_id', Int64),
        ('applicant_name', String),
        ('email', String),
        ('company', String),
        ('industry', String),
        ('job_title', String),
        ('location', String),
        ('source', String),
        ('application_date', String),
        ('stage', String),
        ('salary_expected', Int64),
        ('recruiter', String),
        ('interview_date', String),
        ('notes', String)])

In [20]:
df_.shape

(20, 14)

## Dropping PII cols and irrelevant cols

Within the dataset, there PII columns in there, specifically, `applicant details`, `recruiters`. Since we don't want this senstive data in our data warehouse, we're going to remove it.

We are only going to leave the applicant id for identity of a given application. All of the recruiters detail, however, will be removed, since it gives no analytical insigts later on, not unless, we are creating an internal level to give insights about employee performance. Since we are not, we are going to remove such column. 

On top of this, the `notes` column also yields no analytical insight either. Since this will be irrelevant now, we will also remove this one.

In [15]:
cols_to_remove = ["applicant_name", "email", "recruiter","notes"]
df_safe = df_.drop(cols_to_remove)

df_safe.head(2)

shape: (2, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ applicatio ┆ company   ┆ industry  ┆ job_title ┆ … ┆ applicati ┆ stage   ┆ salary_ex ┆ interview │
│ n_id       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ on_date   ┆ ---     ┆ pected    ┆ _date     │
│ ---        ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ str     ┆ ---       ┆ ---       │
│ i64        ┆           ┆           ┆           ┆   ┆ str       ┆         ┆ i64       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 1          ┆ FoodHub   ┆ Food      ┆ Backend   ┆ … ┆ 13/07/202 ┆ Applied ┆ 45000     ┆ null      │
│            ┆ PH        ┆           ┆ Developer ┆   ┆ 6         ┆         ┆           ┆           │
│ 2          ┆ GreenCart ┆ E-commerc ┆ Software  ┆ … ┆ 13/01/202 ┆ Applied ┆ 45000     ┆ null      │
│            ┆ PH        ┆ e         ┆ Engineer  ┆   ┆ 6         ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘